### ISSUE TITLE
GetMileageSum function Error

### ISSUE THREAD

**Issue by stories2** [djangoServer/djangoServer#13]
>Error

returned None instead Error

>Input

customerAndStoreRegisteredId = 1

**Comment by Asdran** [comment]
url(r'GetMileageSum/$', MileageManager.GetMileageSum),#총 마일리지 누적량을 반환
to change
url(r'^GetMileageSum/$', MileageManager.GetMileageSum),#총 마일리지 누적량을 반환
        wt...

**Comment by stories2** [comment]
> ValueError at /Smoothie/2/GetMileageSum/
The view BackEnd.MileageManager.GetMileageSum didn't return an HttpResponse object. It returned None instead.
Request Method:	GET
Request URL:	http://stories2.iptime.org:4200/Smoothie/2/GetMileageSum/?customerAndStoreRegisteredId=1
Django Version:	1.10.2
Exception Type:	ValueError
Exception Value:	
The view BackEnd.MileageManager.GetMileageSum didn't return an HttpResponse object. It returned None instead.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response, line 198
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/home/stories2/djangoServer/webService',
 '/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Sat, 11 Feb 2017 11:59:34 +0000

Still not fixed error

**Comment by stories2** [comment]
Error Fixed at : fce395a69cb574d9f4ca21e49ff35d2e6ee7de90
