### ISSUE TITLE
서버 터지고 생긴 문제

### ISSUE THREAD

**Issue by Asdran** [djangoServer/djangoServer#16]
예측 사항 이지만

DB에 명령어가 제대로 전송되지 않음
or
DB에서 리턴값이 제대로 전송되지 않음

둘중에 하나일 가능성은 99%

**Comment by stories2** [comment]
망할

**Comment by stories2** [comment]
현제 [스택오버플로우](http://stackoverflow.com/questions/42450968/cant-connect-mariadb-from-remote-client)에 문제 해결 도움 요청중
추가 발견사항으로는 mariadb 포트가 열리지 않는 문제가 있음

    21/tcp   closed ftp

    22/tcp   open   ssh

    23/tcp   closed telnet

    80/tcp   open   http

    443/tcp  closed https

    3306/tcp closed mysql

    8080/tcp closed http-proxy

따라서 급하게 해결하는 방법으로는 서버에 직접 프로그램을 실행 시키면 됨

**Comment by stories2** [comment]
mariadb 설정 파일의 내용 중
`bind-address           = 127.0.0.1`
을
`#bind-address           = 127.0.0.1`
주석처리 한 후 
`/etc/init.d/mysql restart`
서비스 재시작을 진행했더니
`tcp6       0      0 :::3306                 :::*                    LISTEN      -`
정상 작동을 확인함
