### ISSUE TITLE
Write Api document

### ISSUE THREAD

**Issue by stories2** [djangoServer/djangoServer#21]
매장에 등록된 고객들의 정보 리스트를 반환하는 내용에 대한 api문서 업데이트가 필요함
dceb029646eb70bb7ef98417470d7ad1fd6b930b

**Comment by Asdran** [comment]
서버 장비의 문제로 정확한 api 문서 업데이트 불가능 하여 복구 완료 후 작업함

**Comment by stories2** [comment]
서버 장비 임시 복구
도메인 : `stories3.iptime.org`
서버 이전에 따른 소스 업데이트 완료 45a909ad1c27b9fa99d9abaafd56a827db5c6787
[phpmyadmin](http://stories3.iptime.org/mariadb)

**Comment by Asdran** [comment]
1차적 으로 작성은 햇는데 Postman의 사용법을 모르겟어서 이쁘지는 않음

**Comment by stories2** [comment]
## 서버 API 데이터 시트
[서버 데이터베이스 시트](https://docs.google.com/document/d/1fbzL2NHjN-HIzMGbHUh4M0Ye_eysgHa7CQf1bhNULbQ/edit#)

## 변경된 내역
- `매장과 고객 관련`의 `검색 매장에 등록되어있는 모든 회원을 조회`기능

## 리뷰
- API 사용자인 클라이언트에게 확인 후 괜찮다는 응답을 들음
