### ISSUE TITLE
Return Added Customer Info to Store Limitly

### ISSUE THREAD

**Issue by stories2** [djangoServer/djangoServer#22]
## 문제가 되는 부분
- 매장과 고객간 등록된 회원정보를 반환하는 기능 dceb029646eb70bb7ef98417470d7ad1fd6b930b

## 변경 요구 사항
- 회원정보를 리턴할 시 기존에 추가됬다고 알려줬었던 사람들까지도 모두 리턴하던 하던 내용을 최근에 추가된 회원정보들만 리턴하도록 변경

## 기대하는 변경된 형태
- /Smoothie/2/GetCustomerRegisteredInfo/?storeId=<매장 번호>&count=<매장이 가지고 있는 회원 정보 갯수>

## 처리 방법
- 매장(매장 번호 1)에서 이미 다운로드 받아둔 회원들의 정보가 5개이고 서버에 해당 매장(매장 번호 1)에 등록된 고객이 8명이라고 친다
- 매장(매장 번호 1) 에서 서버에 storeId=1&count=5라고 서버에 데이터를 전송한다
- 서버는 이를 받아 해당 매장(매장 번호 1) 에 등록된 총 회원들의 갯수를 비교한다
- 8 - 5 = 3 이므로 3명의 고객정보를 매장(매장 번호 1) 이 못받았다는 걸 확인한다
- 데이터베이스에서 최근에 등록된 고객들 3명의 정보만 매장(매장 번호 1)에 리턴한다

## 처리를 위한 데이터베이스 매장등록 정보 테이블 구조 변경 내역
- 추가된 날짜 라는 컬럼이 추가됨
```
+--------------------+--------------+------+-----+----------------------+-------+    
| Field              | Type         | Null | Key | Default              | Extra |                     
+--------------------+--------------+------+-----+----------------------+-------+                     
| 고유등록번호          | int(11)      | NO   | PRI | NULL                 |       |                     
| 회원번호             | int(11)      | NO   | UNI | NULL                 |       |                     
| 매장번호             | int(11)      | NO   | UNI | NULL                 |       |                     
| 회원탈퇴여부          | tinyint(1)   | YES  |     | 0                    |       |                     
| 추가된 날짜           | timestamp(6) | YES  |     | CURRENT_TIMESTAMP(6) |       |                     
+--------------------+--------------+------+-----+----------------------+-------+
```

**Comment by Asdran** [comment]
받는 값을 count가 아니라 Date를 텍스트 형식으로 건내 받아서 그 이후 것들을 돌려 보내 주는 형식으로 바꿈

**Comment by Asdran** [comment]
상세 정보 : 기준 날짜를 클라이언트 쪽에서 발송 해 주면 그 기준 날짜 이후에 수정된 회원 정보에 한해서만 클라이언트에게 보내줌
