### ISSUE TITLE
Database model need refactoring

### ISSUE THREAD

**Issue by Asdran** [djangoServer/djangoServer#26]
"매장 번호"는 "매장등록 정보" 를 제외한 모든 테이블에서 UNIQUE를 하지 말것
"회원 번호"는 "회원정보" 를 제외한 모든 테이블에서 UNIQUE를 하지 말것

**Comment by stories2** [comment]
외래키가 이미 설정되어 있어 바꾸지 못함

**Comment by stories2** [comment]
## Problem File Name
서버데이터베이스모델.mwb
## Expected behavior
Some table can be overlapped.
## Actual behavior
Every table data are unique.
## Steps to reproduce the behavior
```
Insert into `매장공지 정보` (`매장번호`, `공지번호`) values(1, 2)
```
## Program printed log
```
#1062 - Duplicate entry '1' for key '매장번호_UNIQUE'
```
